clc;
clear;
disp('Lista de sistemas lineares: Exercicio 1 letra (a)');
disp('Para esse exercicio iremos carregar 3 matrizes diferentes e analizar a esparsidade de cada uma e suas respectivas decomposicoes');
input ("Pressione enter para plotar a primeira matriz dos coeficientes A");
load ("./matrizes/plat362.mat");
A = Problem.A;
[L, U, P] = lu(A);
figure(1);
spy(A);
input("Pressione enter para plotar a matriz de decomposicao inferior L");
clf;
figure(2);
spy(L);
input("Pressione enter para plotar a matriz de decomposicao superior U");
figure(3);
spy(U);
disp('comentarios sobre a saida');
input("Pressione enter para prosseguir para proxima matriz");
clf;
input('aperte qualquer tecla para plotar a segunda matriz dos coeficientes A');
load ("./matrizes/rail_5177.mat");
A = Problem.A;
[L, U, P] = lu(A);
figure(1);
spy(A);
input("Pressione enter para plotar a matriz de decomposicao inferior L");
clf;
figure(2);
spy(L);
input("Pressione enter para plotar a matriz de decomposicao superior U");
figure(3);
spy(U);
disp('comentarios sobre a saida');
input("Pressione enter para prosseguir para proxima matriz");
clf;
input('aperte qualquer tecla para plotar a terceira matriz dos coeficientes A');
load ("./matrizes/orsirr_1.mat");
A = Problem.A;
[L, U, P] = lu(A);
figure(1);
spy(A);
input("Pressione enter para plotar a matriz de decomposicao inferior L");
clf;
figure(2);
spy(L);
input("Pressione enter para plotar a matriz de decomposicao superior U");
figure(3);
spy(U);
disp('comentarios sobre a saida');
input("Pressione enter para finalizar a letra (a) do exercicio 1");
clf;