clc;
clear;
disp('Lista de sistemas lineares: Exercicio 1 letra (a)');
disp('Para esse exercicio iremos carregar 3 matrizes diferentes e analizar a esparsidade de cada uma e suas respectivas decomposicoes');
input ("Pressione enter para plotar as matrizes dos coeficientes A");
load ("./matrizes/plat362.mat");
A = Problem.A;
load ("./matrizes/rail_5177.mat");
B = Problem.A;
load ("./matrizes/orsirr_1.mat");
C = Problem.A;
figure(1);
spy(A);
figure(2);
spy(B);
figure(3);
spy(C);
disp('Como podemos perceber todas as tres matrizes dos coeficientes tem disposicoes diferentes.');

input("Pressione enter para plotar as matriz de decomposicao inferior L.");
clf;
[LA, UA, PA] = lu(A);
[LB, UB, PB] = lu(B);
[LC, UC, PC] = lu(C);
figure(1);
spy(LA);
figure(2);
spy(LB);
figure(3);
spy(LC);
disp('Como podemos perceber todas as tres matrizes sao triangulares inferiores.');

input("Pressione enter para plotar as matriz de decomposicao superior U.");
clf;
figure(1);
spy(UA);
figure(2);
spy(UB);
figure(3);
spy(UC);
disp('Como podemos perceber todas as tres matrizes sao triangulares superiores.');

disp('Pode-se concluir que independente da disposicao dos valores das matrizes dos coeficientes as matrizes L e U tem o mesmo formato.');
input("Pressione enter para finalizar a letra (a) do exercicio 1");
clc;
clear;

disp('Lista de sistemas lineares: Exercicio 1 letra (b)');
disp('Para esse exercicio iremos utilizar as mesmas matrizes, calcular a solucao para b igual um vetor de 1 e calcular a norma maxima');
BA = A*ones(n,1);
BB = B*ones(n,1);
BC = C*ones(n,1);